### ISSUE TITLE
Submissions that contain German umlauts do not compile

### ISSUE THREAD

**Issue by TimDaub** [arXiv/arxiv-submission-core#78]
**Describe the bug**
Hello, my name is "Tim Daubensch**ü**tz". And I tried to submit a paper with this name, but every time I tried, I got this error:

```
TeX capacity exceeded, sorry [input stack size=5000]
```
from your compiler.

It's being talked about here too: https://tex.stackexchange.com/a/64924
**To Reproduce**
1. create paper.tex and add an "ü" somewhere
2. Try to submit to arxiv

**Expected behavior**
I expect that any unicode character can be used to submit a paper. Maybe there's already babys named "🌵 ", lol.

**Comment by jweiskoff** [comment]
@TimDaub The stackexchange link you provides is based on a tex tree that's nearly 10 years old (and it's issue seems likely utf8 character encoding within an explicit latin1 encoded document). The extended character set (emojis, specifically) are not yet a part of arXiv's tex tree and including them may cause the behavior. Standard umlauts such as "ü", are fine to include, but typically require the line `\usepackage[utf8]{inputenc}` be included in the preamble (this will likely change to be the default once we move off of texlive 2016).

If your issue is related to an existing submission, please contact help@arxiv.org for assistance.
